-- Rename tov (was "to", reserved word)
ALTER TABLE "PlayerGameStat" RENAME COLUMN "to" TO "tov";

-- Rename tpm/tpa to fg3m/fg3a
ALTER TABLE "PlayerGameStat" RENAME COLUMN "tpm" TO "fg3m";
ALTER TABLE "PlayerGameStat" RENAME COLUMN "tpa" TO "fg3a";

-- Add new columns
ALTER TABLE "PlayerGameStat"
  ADD COLUMN IF NOT EXISTS "orb"  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "drb"  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "fg2m" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "fg2a" INTEGER NOT NULL DEFAULT 0;

-- Add new aggregate columns
ALTER TABLE "PlayerSeasonAggregate"
  ADD COLUMN IF NOT EXISTS "orbAvg" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "drbAvg" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "fg2Pct" DOUBLE PRECISION NOT NULL DEFAULT 0;
