export const RAW_PLAYERS = [
  { id: "p1",  number: 0,  name: "Alexandros Kougianos",      position: "PF/C"     },
  { id: "p2",  number: 3,  name: "Stathis Christofilopoulos", position: "SG"       },
  { id: "p3",  number: 5,  name: "P. Zermpinos",               position: "C"        },
  { id: "p4",  number: 6,  name: "Nikos Tsiardakas",          position: "PG/SG"    },
  { id: "p5",  number: 8,  name: "Spyros Papaspyrou",         position: "PG"       },
  { id: "p6",  number: 9,  name: "Dimitris Alevizos",         position: "SG"       },
  { id: "p7",  number: 10, name: "Loukas Margaritis",         position: "C"        },
  { id: "p8",  number: 11, name: "Giorgos Antonakos",         position: "PG"       },
  { id: "p9",  number: 14, name: "Giorgos Tsioulkas",         position: "SF/PF"    },
  { id: "p10", number: 19, name: "Panagiotis Antonakos",      position: "PG/SG/SF" },
  { id: "p11", number: 23, name: "Konstantinos Psillas",      position: "PG/SG"    },
  { id: "p12", number: 26, name: "Tolis Michalopoulos",       position: "SG/SF"    },
  { id: "p13", number: 77, name: "Andreas Papadimitriou",     position: "PG/SG"    },
];
